### ISSUE TITLE
probleme installation with liferay 6.1 CE

### ISSUE THREAD

**Issue by virginieJ** [cm0s/iframe-plus-portlet#4]
When I try to install the .war file, I have a problem :
13:02:47,011 INFO  [AutoDeployDir:167] Processing iframe-plus-portlet-0.3.0.war
13:02:47,102 INFO  [PortletAutoDeployListener:71] Copying portlets for C:\Utilit
aires\liferay-portal-6.1.0-ce-ga1\deploy\iframe-plus-portlet-0.3.0.war
  Expanding: C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\deploy\iframe-plus-portl
et-0.3.0.war into C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\temp\
20120607130247114
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\tem
p\20120607130247114\WEB-INF
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\tem
p\20120607130247114\WEB-INF\classes
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\tem
p\20120607130247114\WEB-INF\classes
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\tem
p\20120607130247114\META-INF
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\tem
p\20120607130247114\WEB-INF\jsp
13:02:48,283 ERROR [BaseDeployer:322] Unable to copy portal TLD liferay-aui.tld
java.lang.NullPointerException
        at java.io.File.<init>(File.java:222)
        at com.liferay.portal.util.FileImpl.copyFile(FileImpl.java:161)
        at com.liferay.portal.kernel.util.FileUtil.copyFile(FileUtil.java:54)
        at com.liferay.portal.tools.deploy.BaseDeployer.copyPortalDependencies(B
aseDeployer.java:318)
        at com.liferay.portal.tools.deploy.BaseDeployer.deployDirectory(BaseDepl
oyer.java:524)
        at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.
java:889)
        at com.liferay.portal.tools.deploy.BaseDeployer.deployFile(BaseDeployer.
java:819)
        at com.liferay.portal.deploy.auto.PortletAutoDeployer.autoDeploy(Portlet
AutoDeployer.java:96)
        at com.liferay.portal.deploy.auto.PortletAutoDeployListener.deploy(Portl
etAutoDeployListener.java:78)
        at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.processFile(AutoD
eployDir.java:180)
        at com.liferay.portal.kernel.deploy.auto.AutoDeployDir.scanDirectory(Aut
oDeployDir.java:222)
        at com.liferay.portal.kernel.deploy.auto.AutoDeployScanner.run(AutoDeplo
yScanner.java:50)
  Copying 62 files to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\w
ebapps\iframe-plus-portlet
7 juin 2012 13:02:49 org.apache.catalina.startup.HostConfig deployDirectory
INFO: D├®ploiement du r├®pertoire C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tom
cat-7.0.23\webapps\iframe-plus-portlet de l'application web
  Copied 31 empty directories to 1 empty directory under C:\Utilitaires\liferay-
portal-6.1.0-ce-ga1\tomcat-7.0.23\webapps\iframe-plus-portlet
  Copying 1 file to C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\web
apps\iframe-plus-portlet
  Deleting directory C:\Utilitaires\liferay-portal-6.1.0-ce-ga1\tomcat-7.0.23\te
mp\20120607130247114
13:02:49,311 INFO  [PortletAutoDeployListener:81] Portlets for C:\Utilitaires\li
feray-portal-6.1.0-ce-ga1\deploy\iframe-plus-portlet-0.3.0.war copied successful
ly. Deployment will start in a few seconds.

**Comment by cm0s** [comment]
The "liferay-aui.tld" library is deprecated in the Liferay 6.1 CE version. I'm going to modifiy the dependency to replace the "liferay-aui.tld" to the new renamed library "aui.tld". 

Liferay related issue : http://issues.liferay.com/browse/LPS-25302

**Comment by cm0s** [comment]
Bug corrected with the hotfix v0.3.1
